[tool.poetry]
name = "zrm"
version = "0.1.0"
description = "Sync Zotero attachments back-and-forth with your ReMarkable tablet"
authors = ["Laura Brekelmans <mail@laura.fm>"]
license = "gplv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pymupdf = "^1.23.5"
tqdm = "^4.66.3"
pyyaml = "6.0.2"
webdavclient3 = "^3.14.6"
pyzotero = "^1.6.11"
remarks = { git = "https://github.com/Scrybbling-together/remarks", branch = "main" }
jinja2 = "^3.1.6"
pytest = "^8.0.0"
lxml = "^6.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
zrm = "zrm.zotero_rm_bridge:main"

[tool.pytest.ini_options]
markers = [
    "e2e: end-to-end tests with real reMarkable and Zotero accounts",
    "mock: fast unit tests using mock APIs"
]

[tool.mypy]
mypy_path = "typings"
